# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: setup ci
        run: |
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         git config --global gc.auto 0
      
      - name: patch
        run: ./patch.sh
        
      - name: tar
        run: tar -czvf linux-kernel.tar.gz linux
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: source
          path: linux-kernel.tar.gz
        
